jobs:
  - job: Test
    pool:
      vmImage: 'Ubuntu 16.04'
    variables:
      NODE_VERSION: 12.16.1
      SPRING_OUTPUT_ANSI_ENABLED: NEVER
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true
      GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle

    steps:
      - task: Cache@2
        inputs:
          key: 'gradle | "$(Agent.OS)"'
          restoreKeys: gradle
          path: $(GRADLE_USER_HOME)
        displayName: Gradle build cache
      - script: |
          ./gradlew checkstyleNohttp
          ./gradlew clean test integrationTest
        displayName: 'Tests'
      - script: |
          ./gradlew --build-cache build -x test integrationTest
        displayName: 'Build'
      - script: |
          ./gradlew bootJar -Pprod -x test
        displayName: 'Package'
      - script: |
          ./gradlew --stop
        displayName: 'Gradle daemon stop'
